In [59]:
import numpy.matlib
import numpy as np


#simple array
a1 = np.array([1,2,3])
print(a1)

#A 2d array
a2 = np.array([['a','b','c'], [4,5,6]])
print(a2)

#Give minimum array dimensions
a3 = np.array([4,5,6,3,5,9], ndmin=2)
print(a3)

#define dtype parameter as complex
a4 = np.array([6,9,2], dtype = complex)
print(a4)

######  Array Attributes ########
a5 = np.array([[1,2,3],[4,5,6]])
print(a5.shape)

a5.shape = (3,2)
print(a5)
a5_1 = a5.reshape(3,2)
print(a5_1)
print (a5.flags)

#Empty array with out initializing values might be filled with previous numbers
x = np.empty([3,2], dtype = int) 
print (x)

#Indexing and slicing
a = np.arange(10) 
print(a)
s = slice(2,7,2) 
print (a[s])

aa = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(aa)  
ab = slice(1,2,2)
print(ab)
# slice items starting from index
print('Now we will slice the array from the index aa[1:]') 
print(aa[1:])

#Array Broadcasting
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

# Broadcasting when array size 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  

print('first array\n', a);
print('second array\n', b);
print('Summation of the two arrays #array_broadcasting')
print(a+b);

#Iterating over ndarray using nditer
a = np.arange(0,60,5)
a = a.reshape(3,4)
print('Original array\n',a)
for e in np.nditer(a):
    print(e);
#Array sorting , Order parameter in sort function 
dt = np.dtype([('name', 'S10'),('age', int)]) 
a = np.array([("ranga",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt) 
print('Original unsorted array \n', a)
a = np.sort(a, order= 'name')
print('Sorted array \n', a)

# NumPy package contains a Matrix library numpy.matlib

print('Empty matrix \n',np.matlib.empty((2,2)))
print('Zeros \n',np.matlib.zeros((2,2)))
print('Ones \n',np.matlib.ones((2,2)))
print('np.matlib.eye(n = 3, M = 4, k = 0, dtype = float)\n', np.matlib.eye(n = 3, M = 4, k = 0, dtype = float))
# numpy.matlib.identity() function returns the Identity matrix of the given size
print('np.matlib.identity(5, dtype = float)\n', np.matlib.identity(5, dtype = float))
# numpy.matlib.rand() function returns a matrix of the given size filled with random values.
print('np.matlib.rand(3,3)\n', np.matlib.rand(3,3))


[1 2 3]
[['a' 'b' 'c']
 ['4' '5' '6']]
[[4 5 6 3 5 9]]
[6.+0.j 9.+0.j 2.+0.j]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
[[1 2]
 [3 4]
 [5 6]]
[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[[1 2 3]
 [3 4 5]
 [4 5 6]]
slice(1, 2, 2)
Now we will slice the array from the index aa[1:]
[[3 4 5]
 [4 5 6]]
[ 10  40  90 160]
first array
 [[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
second array
 [1. 2. 3.]
Summation of the two arrays #array_broadcasting
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
Original array
 [[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0
5
10
15
20
25
30
35
40
45
50
55
Original unsorted array 
 [(b'ranga', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]
Sorted array 
 [(b'amar', 27) (b'anil', 25) (b'ranga', 21) (b'ravi', 17)]
Empty matrix 
 [[1. 1.]
 [1. 1.]]
Zeros 
 [[0. 0.]
 [0. 0.]]
Ones 
 [[1. 1.]
 [